/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conversor;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Tobias
 */
public class ConversorGenerico extends javax.swing.JFrame {

    private List<Conversor> conversores = new ArrayList<Conversor>();
    private Conversor conversorSeleccionado = null;
    private boolean txtValor1Modificado = false;

    /**
     * Creates new form ConversorGenerico
     */
    public ConversorGenerico() {
        initComponents();
        setLocationRelativeTo(null);
        conversores.add(new CentimetrosAPulgadasConversor());
        conversores.add(new MetrosAKilometrosConversor());
        conversores.add(new CentigradosAFahrenheitConversor());
        conversores.add(new KilometrosPorHoraAMillasPorHoraConversor());
        conversores.add(new LitrosAGalonConversor());
        btnConvertir.setText("Convertir");

        for (Conversor conversor : conversores) {
            cmbSeleccionarUnidades.addItem(conversor.toString());
        }
    }

    private void convertir() {
        try {
            if (txtValor1Modificado) {
                double valor1 = Double.parseDouble(txtValor1.getText().replace(",", "."));
                txtValor2.setText(String.format("%.2f", this.conversorSeleccionado.ConvertirSegunValor1(valor1)));
            } else {
                double valor2 = Double.parseDouble(txtValor2.getText().replace(",", "."));
                txtValor1.setText(String.format("%.2f", this.conversorSeleccionado.ConvertirSegunValor2(valor2)));
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error al convertir", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreValor1 = new javax.swing.JLabel();
        lblNombreValor2 = new javax.swing.JLabel();
        cmbSeleccionarUnidades = new javax.swing.JComboBox<>();
        btnConvertir = new javax.swing.JButton();
        txtValor1 = new javax.swing.JTextField();
        txtValor2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNombreValor1.setText("jLabel1");

        lblNombreValor2.setText("jLabel2");

        cmbSeleccionarUnidades.setToolTipText("");
        cmbSeleccionarUnidades.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSeleccionarUnidadesItemStateChanged(evt);
            }
        });
        cmbSeleccionarUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSeleccionarUnidadesActionPerformed(evt);
            }
        });

        btnConvertir.setText("jButton1");
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });

        txtValor1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValor1FocusLost(evt);
            }
        });
        txtValor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValor1ActionPerformed(evt);
            }
        });
        txtValor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValor1KeyPressed(evt);
            }
        });

        txtValor2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValor2FocusLost(evt);
            }
        });
        txtValor2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValor2KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnConvertir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbSeleccionarUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombreValor2)
                                    .addComponent(lblNombreValor1))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtValor1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtValor2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 33, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbSeleccionarUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreValor1)
                    .addComponent(txtValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(btnConvertir)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreValor2)
                    .addComponent(txtValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        this.convertir();
    }//GEN-LAST:event_btnConvertirActionPerformed

    private void cmbSeleccionarUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSeleccionarUnidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSeleccionarUnidadesActionPerformed

    private void cmbSeleccionarUnidadesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSeleccionarUnidadesItemStateChanged

        this.conversorSeleccionado = conversores.get(cmbSeleccionarUnidades.getSelectedIndex());

        lblNombreValor1.setText(conversorSeleccionado.getLabelValor1());
        lblNombreValor2.setText(conversorSeleccionado.getLabelValor2());
    }//GEN-LAST:event_cmbSeleccionarUnidadesItemStateChanged

    private void txtValor1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValor1FocusLost
        this.txtValor1Modificado = true;
    }//GEN-LAST:event_txtValor1FocusLost

    private void txtValor2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValor2FocusLost
        this.txtValor1Modificado = false;
    }//GEN-LAST:event_txtValor2FocusLost

    private void txtValor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValor1ActionPerformed

    private void txtValor1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValor1KeyPressed
        // TODO add your handling code here:        
        this.txtValor1Modificado = true;
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.convertir();
        }
    }//GEN-LAST:event_txtValor1KeyPressed

    private void txtValor2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValor2KeyPressed
        // TODO add your handling code here:
        this.txtValor1Modificado = false;
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.convertir();
        }
    }//GEN-LAST:event_txtValor2KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversorGenerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversorGenerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversorGenerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversorGenerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversorGenerico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertir;
    private javax.swing.JComboBox<String> cmbSeleccionarUnidades;
    private javax.swing.JLabel lblNombreValor1;
    private javax.swing.JLabel lblNombreValor2;
    private javax.swing.JTextField txtValor1;
    private javax.swing.JTextField txtValor2;
    // End of variables declaration//GEN-END:variables
}
